### ISSUE TITLE
Python examples?

### ISSUE THREAD

**Issue by frankgould** [waveshare/Power-Management-HAT#1]
The wiki has no details about python examples and use. The python script provided only reads on GPIO pin to determine to shutdown the Pi. Where can I get details how to use this board, with python especially to read voltage/current? I don't see what battery to install on the board to enable the RTC feature, if required. I have a WaveShare PM UPS HAT board, now I want to use it but cannot.

**Comment by Jensen67** [comment]
> The wiki has no details about python examples and use. The python script provided only reads on GPIO pin to determine to shutdown the Pi. Where can I get details how to use this board, with python especially to read voltage/current? I don't see what battery to install on the board to enable the RTC feature, if required. I have a WaveShare PM UPS HAT board, now I want to use it but cannot.

If you are using this board, https://www.waveshare.com/wiki/Power_Management_HAT 
use a CR1220 battery.

**Comment by frankgould** [comment]
This product description is misleading. To control the HAT, one must use an Arduino. It will NOT work with Raspberry Pi as a switchable power supply that will shutdown when power reserve is too low and informing the user of this action.
